name: Linux tests

on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
          sudo apt-get install -y cmake g++ make gcc

      - name: Run tests
        run: sudo scripts/build_and_run_unit_tests.bash
